//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANGCONG()
        {
            this.LUONG1 = new HashSet<LUONG1>();
        }
    
        public int MAC { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> CONGLE { get; set; }
        public Nullable<int> NGHICP { get; set; }
        public Nullable<int> NGHIKP { get; set; }
        public Nullable<int> CONGTHUONG { get; set; }
        public Nullable<int> CONGCN { get; set; }
        public Nullable<int> TONGC { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONG1> LUONG1 { get; set; }
    }
}
