//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOPDONG()
        {
            this.QUATRINHLENLUONGs = new HashSet<QUATRINHLENLUONG>();
        }
    
        public int MAHD { get; set; }
        public int MANV { get; set; }
        public string LOAIHD { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public Nullable<System.DateTime> TGLV { get; set; }
        public Nullable<System.DateTime> NGAYKY { get; set; }
        public Nullable<double> HESOLUONG { get; set; }
        public Nullable<double> LUONGCB { get; set; }
        public Nullable<double> PHUCAP { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUATRINHLENLUONG> QUATRINHLENLUONGs { get; set; }
    }
}
