//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSOTD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSOTD()
        {
            this.KQTDs = new HashSet<KQTD>();
        }
    
        public int MAHS { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string CCCD { get; set; }
        public string SDT { get; set; }
        public Nullable<int> MADT { get; set; }
        public Nullable<int> MATG { get; set; }
        public Nullable<int> MATD { get; set; }
        public Nullable<int> MAVTTD { get; set; }
        public Nullable<System.DateTime> NGAYTD { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string Email { get; set; }
        public byte[] CVContent { get; set; }
        public string FileCV { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual DANTOC DANTOC { get; set; }
        public virtual TONGIAO TONGIAO { get; set; }
        public virtual TRINHDO TRINHDO { get; set; }
        public virtual VITRITUYEN VITRITUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KQTD> KQTDs { get; set; }
    }
}
