//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQTD
    {
        public int MAKQTD { get; set; }
        public Nullable<int> MAHOSO { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<int> PHONGBAN { get; set; }
        public Nullable<System.DateTime> NGAYTD { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> BOPHAN { get; set; }
        public Nullable<int> CHUCVU { get; set; }
    
        public virtual BOPHAN BOPHAN1 { get; set; }
        public virtual CHUCVU CHUCVU1 { get; set; }
        public virtual HOSOTD HOSOTD { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONGBAN PHONGBAN1 { get; set; }
    }
}
