//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYLUAT
    {
        public int MAKL { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<System.DateTime> NGAYKL { get; set; }
        public string HINHTHUCKL { get; set; }
        public string LYDOKL { get; set; }
        public string NOIDUNG { get; set; }
        public string LOAI { get; set; }
        public Nullable<double> SOTIEN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
