//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG1
    {
        public int MAL { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<double> HSL { get; set; }
        public Nullable<double> LUONGCB { get; set; }
        public Nullable<double> PHUCAP { get; set; }
        public Nullable<double> TULUONG { get; set; }
        public Nullable<double> TIENKB { get; set; }
        public Nullable<double> TTIENKL { get; set; }
        public Nullable<double> TONGLANH { get; set; }
        public Nullable<int> MAC { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
    
        public virtual BANGCONG BANGCONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
