//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BANGCONGs = new HashSet<BANGCONG>();
            this.BAOHIEMs = new HashSet<BAOHIEM>();
            this.CHAMCONGs = new HashSet<CHAMCONG>();
            this.HOPDONGs = new HashSet<HOPDONG>();
            this.KHENTHUONGs = new HashSet<KHENTHUONG>();
            this.KQTDs = new HashSet<KQTD>();
            this.KYLUATs = new HashSet<KYLUAT>();
            this.LUONG1 = new HashSet<LUONG1>();
            this.NV_PHUCAP = new HashSet<NV_PHUCAP>();
            this.QUATRINHCONGTACs = new HashSet<QUATRINHCONGTAC>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.THOIVIECs = new HashSet<THOIVIEC>();
            this.TRULUONGs = new HashSet<TRULUONG>();
        }
    
        public int MANV { get; set; }
        public string HOTEN { get; set; }
        public string HINHANH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<int> MADT { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public string GIOITINH { get; set; }
        public string DIENTHOAI { get; set; }
        public Nullable<int> MAPB { get; set; }
        public Nullable<int> MABP { get; set; }
        public Nullable<int> MACV { get; set; }
        public Nullable<int> MATDHV { get; set; }
        public Nullable<int> MATG { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANGCONG> BANGCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHIEM> BAOHIEMs { get; set; }
        public virtual BOPHAN BOPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual DANTOC DANTOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHENTHUONG> KHENTHUONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KQTD> KQTDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYLUAT> KYLUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONG1> LUONG1 { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual TONGIAO TONGIAO { get; set; }
        public virtual TRINHDO TRINHDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NV_PHUCAP> NV_PHUCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUATRINHCONGTAC> QUATRINHCONGTACs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIVIEC> THOIVIECs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRULUONG> TRULUONGs { get; set; }
    }
}
