//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUATRINHLENLUONG_CHITIET
    {
        public int MAQDCT { get; set; }
        public Nullable<int> MAQD { get; set; }
        public Nullable<double> HESOLUONG { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
    }
}
