//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIVIEC
    {
        public int MANVIEC { get; set; }
        public int MANV { get; set; }
        public Nullable<System.DateTime> NGAYNOPDON { get; set; }
        public Nullable<System.DateTime> NGAYTV { get; set; }
        public string LYDOTV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
