//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlynhansu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VITRITUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VITRITUYEN()
        {
            this.HOSOTDs = new HashSet<HOSOTD>();
        }
    
        public int MAVTTD { get; set; }
        public string TENVTTD { get; set; }
        public string YEUCAU { get; set; }
        public string NOIDUNG { get; set; }
        public string LUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSOTD> HOSOTDs { get; set; }
    }
}
